config/routes.rb
#if Clearance.configuration.routes_enabled?
  Rails.application.routes.draw do

  resources :elections

  resources :volunteers
  # resources :simple_registrations
  # resources :languages
  # resources :country_languages
  # resources :countries
  # resources :city_languages
  # resources :cities
  # resources :status_languages
  # resources :statuses
  # resources :event_languages
  resources :events
  resources :memberships
  resources :articles
  resources :contacts
  resources :certifications
  resources :abouts
  resources :news
  
  get 'admin' => 'admin#index'
 # You can have the root of your site routed with "root"
  root 'news#index'
  

# OI > Authorization  
#    resources :passwords,
#      controller: 'clearance/passwords',
#      only: [:create, :new]

#    resource :session,
#      controller: 'clearance/sessions',
#      only: [:create]

#    resources :users,
#      controller: 'clearance/users',
#      only: Clearance.configuration.user_actions do
#        resource :password,
#          controller: 'clearance/passwords',
#          only: [:create, :edit, :update]
#      end

#   get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
#   delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'

#    if Clearance.configuration.allow_sign_up?
#      get '/sign_up' => 'clearance/users#new', as: 'sign_up'
#    end
  end
#end

app/models/about.rb
class About < ActiveRecord::Base
  belongs_to :language
  validates_presence_of :lang_id
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :language
  validates_presence_of :lang_id
end

app/models/certification.rb
class Certification < ActiveRecord::Base
  belongs_to :language
  validates_presence_of :lang_id
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :events
  has_many :city_languages, dependent: :destroy
  belongs_to :country
end

app/models/city_language.rb
class CityLanguage < ActiveRecord::Base
  belongs_to :city
  belongs_to :language
  validates_presence_of :city_id
  validates_presence_of :lang_id
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :language
  validates_presence_of :lang_id
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :cities, dependent: :destroy
  has_many :country_languages, dependent: :destroy
end

app/models/election.rb
class Election < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :event_languages, :dependent => :destroy
  has_many :city_languages, through: :cities
  has_many :status_languages, through: :status
  belongs_to :status
  belongs_to :city
  validates_presence_of :status_id
  validates_presence_of :city_id  
  accepts_nested_attributes_for :event_languages
  accepts_nested_attributes_for :status_languages
  accepts_nested_attributes_for :status
end

app/models/event_language.rb
class EventLanguage < ActiveRecord::Base
  belongs_to :event
  belongs_to :language
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_many :certifications
  has_many :articles
  has_many :abouts
  has_many :contacts
  has_many :memberships
  has_many :news
  has_many :country_languages
  has_many :city_languages
  has_many :event_languages
  has_many :status_languages
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :language
  validates_presence_of :lang_id
end

app/models/news.rb
class News < ActiveRecord::Base
  belongs_to :language
  validates_presence_of :lang_id
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :status_languages, dependent: :destroy
  has_many :events
end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
  belongs_to :language
  validates_presence_of :lang_id
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/admin/_form_about.erb
<table class='table-admin'>
	<tr>
		<%= link_to new_about_path do %>
		<i class="btn btn-info">Добавить страницу "Об огранизации"</i>
		<% end %> 
		<br><br>
	</tr>
	<tr>
		<th>Заголовок страницы</th>
		<th>Язык</th>
		<th>Дата создания</th>
		<th>Дата последнего обновления</th>
		<th></th>
	</tr>
	<% @abouts.order('id DESC').each do |about| %>
	<tr>
		<td>		
			<p><%= about.title %></p>
   		</td>
		<td>			
			<p><%= about.lang_id %></p>
   		</td>
		<td>			
			<p><%= about.created_at.localtime.to_formatted_s(:db) %></p>
   		</td>
		<td>			
			<p><%= about.updated_at.localtime.to_formatted_s(:db) %></p>
   		</td>
		<td class="admintable_column_operations">
			<div> 
				<%= link_to about, :target => '_blank' do %>
					<i class="fa fa-file-text fa-lg icon btn btn-info operation_buttons"></i>		
				<% end %>
	   			<%= link_to edit_about_path(about) do %>
					<i class="fa fa-pencil fa-lg icon btn btn-info operation_buttons"></i> 
	   			<% end %>
	   			<%= link_to about, method: :delete, data: { confirm: 'Пожалуйста, подтвердите удаление страницы "Об организации"' }  do %>
					<i class="fa fa-trash fa-lg icon btn btn-danger operation_buttons"></i> 
	   			<% end %>
	   		</div>
		</td>
	</tr>
	<% end %>
</table>

app/views/admin/_form_article.erb
<table class='table-admin'>
	<tr>
		<%= link_to new_article_path do %>
		<i class="btn btn-info">Добавить статью</i>
		<% end %> 
		<br><br>
	</tr>
	<tr>
		<th>Заголовок страницы</th>
		<th>Язык</th>
		<th>Дата создания</th>
		<th>Дата последнего обновления</th>
		<th></th>
	</tr>
	<% @articles.order('id DESC').each do |article| %>
		<tr>
		<td>		
			<p><%= article.title %></p>
   		</td>
		<td>			
			<p><%= article.lang_id %></p>
   		</td>
		<td>			
			<p><%= article.created_at.localtime.to_formatted_s(:db) %></p>
   		</td>
		<td>			
			<p><%= article.updated_at.localtime.to_formatted_s(:db) %></p>
   		</td>
		<td class="admintable_column_operations">
			<div> 
				<%= link_to article, :target => '_blank' do %>
					<i class="fa fa-file-text fa-lg icon btn btn-info operation_buttons"></i>		
				<% end %>
	   			<%= link_to edit_article_path(article) do %>
					<i class="fa fa-pencil fa-lg icon btn btn-info operation_buttons"></i> 
	   			<% end %>
	   			<%= link_to article, method: :delete, data: { confirm: 'Пожалуйста, подтвердите удаление статьи' }  do %>
					<i class="fa fa-trash fa-lg icon btn btn-danger operation_buttons"></i> 
	   			<% end %>
	   		</div>
		</td>
	</tr>
	<% end %>
</table>

app/views/admin/_form_certification.erb
<table class='table-admin'>
	<tr>
		<%= link_to new_certification_path do %>
		<i class="btn btn-info">Добавить страницу "Сертификация"</i>
		<% end %> 
		<br><br>
	</tr>
	<tr>
		<th>Заголовок страницы</th>
		<th>Язык</th>
		<th>Дата создания</th>
		<th>Дата последнего обновления</th>
		<th></th>
	</tr>
	
	<% @certifications.order('id DESC').each do |certification| %>
	<tr>
		<td>			
			<p><%= certification.title %></p>
   		</td>
		<td>			
			<p><%= certification.lang_id %></p>
   		</td>
		<td>			
			<p><%= certification.created_at.localtime.to_formatted_s(:db) %></p>
   		</td>
   		<td>
   			<p><%= certification.updated_at.localtime.to_formatted_s(:db)%></p>
   		</td>
   		
   		<td class="admintable_column_operations">
   			<div> 
				<%= link_to certification, :target => '_blank' do %>
					<i class="fa fa-file-text fa-lg icon btn btn-info operation_buttons"></i>		
				<% end %>
	   			<%= link_to edit_certification_path(certification) do %>
					<i class="fa fa-pencil fa-lg icon btn btn-info operation_buttons"></i> 
	  			<% end %>
	   			<%= link_to certification, method: :delete, data: { confirm: 'Пожалуйста, подтвердите удаление страницы "Сертификация"' }  do %>
					<i class="fa fa-trash fa-lg icon btn btn-danger operation_buttons"></i> 
	   			<% end %>
	   		</div>
		</td>
	</tr>
	<% end %>
</table>

app/views/admin/_form_contact.erb
<table class='table-admin'>
	<tr>
		<%= link_to new_contact_path do %>
		<i class="btn btn-info">Добавить страницу "Контакты"</i>
		<% end %> 
		<br><br>
	</tr>
	<tr>
		<th>Название страницы</th>
		<th>Язык</th>
		<th>Дата создания</th>
		<th>Дата последнего обновления</th>
		<th></th>		
	</tr>
	<% @contacts.order('id DESC').each do |contact| %>
	<tr>
		<td>			
			<p><%= contact.title %></p>
   		</td>
   		<td>
   			<p><%= contact.lang_id %></p>
   		</td>
   		<td>
   			<p><%= contact.created_at.localtime.to_formatted_s(:db) %></p>
   		</td>
   		<td>
   			<p><%= contact.updated_at.localtime.to_formatted_s(:db) %></p>
   		</td>
   		
   		<td class="admintable_column_operations">
   			<div> 
				<%= link_to contact, :target => '_blank' do %>
					<i class="fa fa-file-text fa-lg icon btn btn-info operation_buttons"></i>			
				<% end %>
	   			<%= link_to edit_contact_path(contact) do %>
					<i class="fa fa-pencil fa-lg icon btn btn-info operation_buttons"></i> 
	   			<% end %>
	   			<%= link_to contact, method: :delete, data: { confirm: 'Пожалуйста, подтвердите удаление страницы "Контакты"' }  do %>
					<i class="fa fa-trash fa-lg icon btn btn-danger operation_buttons"></i> 
	   			<% end %>
	   		</div>   			
		</td>
	</tr>
	<% end %>
</table>

app/views/admin/_form_election.erb
<table class='table-admin'>
	<tr>
		<%= link_to new_election_path do %>
		<i class="btn btn-info">Добавить страницу "Выборы"</i>
		<% end %> 
		<br><br>
	</tr>
	<tr>
		<th>Название страницы</th>
		<th>Язык</th>
		<th>Дата создания</th>
		<th>Дата последнего обновления</th>
		<th></th>		
	</tr>
	<% @elections.order('id DESC').each do |election| %>
	<tr>
		<td>			
			<p><%= election.title %></p>
   		</td>
   		<td>
   			<p><%= election.lang_id %></p>
   		</td>
   		<td>
   			<p><%= election.created_at.localtime.to_formatted_s(:db) %></p>
   		</td>
   		<td>
   			<p><%= election.updated_at.localtime.to_formatted_s(:db) %></p>
   		</td>
   		
   		<td class="admintable_column_operations">
   			<div> 
				<%= link_to election, :target => '_blank' do %>
					<i class="fa fa-file-text fa-lg icon btn btn-info operation_buttons"></i>			
				<% end %>
	   			<%= link_to edit_election_path(election) do %>
					<i class="fa fa-pencil fa-lg icon btn btn-info operation_buttons"></i> 
	   			<% end %>
	   			<%= link_to election, method: :delete, data: { confirm: 'Пожалуйста, подтвердите удаление страницы "Выборы"' }  do %>
					<i class="fa fa-trash fa-lg icon btn btn-danger operation_buttons"></i> 
	   			<% end %>
	   		</div>   			
		</td>
	</tr>
	<% end %>
</table>

app/views/admin/_form_event.erb
<table class='table-admin'>
	<tr><%= link_to new_event_path do %>
			<i class="btn btn-info">Добавить мероприятие</i>
		<% end %> 
		<br><br>
	</tr>
	<tr>
		<th>ИД</th>
		<th>Заголовок мероприятия</th>
		<th>Статус</th>
		<th>Дата/время начала</th>
		<th>Дата/время окончания</th>
		<th>Длитель-ность (час.)</th>
		<th>Город</th>
		<th></th>
	</tr>
	<% @events.order('id DESC').each do |event| %>
	<tr>
		<td>
			<p><%= event.id %></p>
   		</td>
		<td>
			<p><%= event.event_languages.first.title %></p>
   		</td>
		<td>			
			<p><%= event.status.status_languages.first.title %></p>
   		</td>
   		<td width="100px">
   			<p><%= event.start_date.to_formatted_s(:rfc822) %></p>
   		</td>
   		<td width="100px">
   			<p><%= event.end_date.to_formatted_s(:rfc822) %></p>
   		</td>
   		<td>
   			<p><%= event.duration %></p>
   		</td>
   		<td>
   			<p><%= event.city.city_languages.first.title %></p>
   		</td>
   		<td class="admintable_column_operations">
   			<div> 
				<%= link_to event, :target => '_blank' do %>
					<i class="fa fa-file-text fa-lg icon btn btn-info operation_buttons"></i>
				<% end %>
				<%= link_to edit_event_path(event) do %>
					<i class="fa fa-pencil fa-lg icon btn btn-info operation_buttons"></i> 
				<% end %>   			
	   			<%= link_to event, method: :delete, data: { confirm: 'Пожалуйста, подтвердите удаление мероприятия' }  do %>
					<i class="fa fa-trash fa-lg icon btn btn-danger operation_buttons"></i>
	   			<% end %>
	   		</div>
		</td>
	</tr>
	<% end %>
</table>

app/views/admin/_form_membership.erb
<table class='table-admin'>
	<tr>
		<%= link_to new_membership_path do %>
		<i class="btn btn-info">Добавить страницу "Членство"</i>
		<% end %> 
		<br><br>
	</tr>
	<tr>
		<th>Заголовок страницы</th>
		<th>Язык</th>
		<th>Дата создания</th>
		<th>Дата последнего обновления</th>
		<th></th>
	</tr>
	<% @memberships.order('id DESC').each do |membership| %>
	<tr>
		<td>		
			<p><%= membership.title %></p>
   		</td>
		<td>			
			<p><%= membership.lang_id %></p>
   		</td>
		<td>			
			<p><%= membership.created_at.localtime.to_formatted_s(:db) %></p>
   		</td>
		<td>			
			<p><%= membership.updated_at.localtime.to_formatted_s(:db) %></p>
   		</td>
		<td class="admintable_column_operations"> 
			<div>
				<%= link_to membership, :target => '_blank' do %>
					<i class="fa fa-file-text fa-lg icon btn btn-info operation_buttons"></i>		
				<% end %>
   				<%= link_to edit_membership_path(membership) do %>
					<i class="fa fa-pencil fa-lg icon btn btn-info operation_buttons"></i> 
   				<% end %>
   				<%= link_to membership, method: :delete, data: { confirm: 'Пожалуйста, подтвердите удаление страницы "Членство"' }  do %>
					<i class="fa fa-trash fa-lg icon btn btn-danger operation_buttons"></i> 
   				<% end %>
   			</div>   			
		</td>
	</tr>
	<% end %>
</table>

app/views/admin/_form_news.erb
<table class='table-admin'>
	<tr><%= link_to new_news_path do %>
			<i class="btn btn-info">Добавить новость</i>
		<% end %> 
		<br><br>
	</tr>
	<tr>
		<th>Заголовок новости</th>
		<th>Язык</th>
		<th>Дата публикации</th>
		<th></th>
	</tr>
	<% @news.order('id DESC').each do |news| %>
	<tr>
		<td>
			<p><%= news.title %></p>
   		</td>
		<td>			
			<p><%= news.lang_id %></p>
   		</td>
		<td>			
			<p><%= news.publish_date.localtime.to_formatted_s(:db) %></p>
   		</td>
   		<td class="admintable_column_operations">
   			<div> 
				<%= link_to news, :target => '_blank' do %>
					<i class="fa fa-file-text fa-lg icon btn btn-info operation_buttons"></i>
				<% end %>
				<%= link_to edit_news_path(news) do %>
					<i class="fa fa-pencil fa-lg icon btn btn-info operation_buttons"></i> 
				<% end %>   			
	   			<%= link_to news, method: :delete, data: { confirm: 'Пожалуйста, подтвердите удаление новости' }  do %>
					<i class="fa fa-trash fa-lg icon btn btn-danger operation_buttons"></i>
	   			<% end %>
	   		</div>
		</td>
	</tr>
	<% end %>
</table>

app/views/admin/_form_volunteer.erb
<table class='table-admin'>
	<tr>
		<%= link_to new_volunteer_path do %>
		<i class="btn btn-info">Добавить страницу "Волонтерство в PMI Ukraine Chapter"</i>
		<% end %> 
		<br><br>
	</tr>
	<tr>
		<th>Заголовок страницы</th>
		<th>Язык</th>
		<th>Дата создания</th>
		<th>Дата последнего обновления</th>
		<th></th>
	</tr>
	<% @volunteers.order('id DESC').each do |volunteer| %>
	<tr>
		<td>		
			<p><%= volunteer.title %></p>
   		</td>
		<td>			
			<p><%= volunteer.lang_id %></p>
   		</td>
		<td>			
			<p><%= volunteer.created_at.localtime.to_formatted_s(:db) %></p>
   		</td>
		<td>			
			<p><%= volunteer.updated_at.localtime.to_formatted_s(:db) %></p>
   		</td>
		<td class="admintable_column_operations">
			<div> 
				<%= link_to volunteer, :target => '_blank' do %>
					<i class="fa fa-file-text fa-lg icon btn btn-info operation_buttons"></i>		
				<% end %>
	   			<%= link_to edit_volunteer_path(volunteer) do %>
					<i class="fa fa-pencil fa-lg icon btn btn-info operation_buttons"></i> 
	   			<% end %>
	   			<%= link_to volunteer, method: :delete, data: { confirm: 'Пожалуйста, подтвердите удаление страницы "Волонтерство в PMI Ukraine Chapter"' }  do %>
					<i class="fa fa-trash fa-lg icon btn btn-danger operation_buttons"></i> 
	   			<% end %>
	   		</div>
		</td>
	</tr>
	<% end %>
</table>

app/views/admin/index.html.erb
<div class="row">	
	<div class="col-md-12 sectioncontainer">
	<h3><b>Admin panel</b></h3>
	</div>
	<div class="col-md-3 sectioncontainer">
		<span>Пожалуйста, выберите раздел:</span>
		<select id="category_id" onchange="category_onchange();">
			<option value="news">Новости</option>
			<option value="abouts">Об организации</option>
			<option value="contacts">Контакты</option>
			<option value="certifications">Сертификация</option>
			<option value="memberships">Членство</option>
			<option value="articles">Статьи</option>
			<option value="events">Мероприятия</option>
			<option value="volunteers">Волонтерство в PMI Ukraine Chapter</option>
			<option value="elections">Выборы</option>
		</select>		
		<% if params['notice']!=nil %>
			<p id="notice" style="padding-top: 15px"> <%= params['notice'] %> </p> 
		<% end %>
	</div>	
	<div class="col-md-9 sectioncontainer" id="content">		
		<%= render 'form_news' if cookies['selected_category_id']=='news' %>
		<%= render 'form_about' if cookies['selected_category_id']=='abouts' %>
		<%= render 'form_certification' if cookies['selected_category_id']=='certifications' %>
		<%= render 'form_contact' if cookies['selected_category_id']=='contacts' %>
		<%= render 'form_membership' if cookies['selected_category_id']=='memberships' %>
		<%= render 'form_article' if cookies['selected_category_id']=='articles' %>
		<%= render 'form_event' if cookies['selected_category_id']=='events' %>
		<%= render 'form_volunteer' if cookies['selected_category_id']=='volunteers' %>
		<%= render 'form_election' if cookies['selected_category_id']=='elections' %>
		<br>
	</div>	
</div>

<script type="text/javascript">

	$(function() {
		var v = document.getElementById('category_id');
		v.value = readCookie('selected_category_id');
		if (v.value == '') {
			v.value = 'news';
			category_onchange();
		};
	});
	
	window.onload = function() {
	}

	function readCookie(name) {
		match = document.cookie.match(new RegExp(name + '=([^;]+)'));
		if (match) return match[1];     
	}
 
	function category_onchange() {
		var v = document.getElementById('category_id');
		document.cookie = 'selected_category_id='+v.value;
		location.reload();
		location.search = '';
	}  
  
  function removeURLParameter(url, parameter) {
		//prefer to use l.search if you have a location/link object
		var urlparts= url.split('?');   
		if (urlparts.length>=2) {
			var prefix= encodeURIComponent(parameter)+'=';
			var pars= urlparts[1].split(/[&;]/g);
			
			//reverse iteration as may be destructive
			for (var i= pars.length; i-- > 0;) {    
				//idiom for string.startsWith
				if (pars[i].lastIndexOf(prefix, 0) !== -1) {  
					pars.splice(i, 1);
				}
			}
			url= urlparts[0]+'?'+pars.join('&');
			return url;
		} else {
			return url;
		}
	}
</script>