config/routes.rb
#if Clearance.configuration.routes_enabled?
  Rails.application.routes.draw do

  resources :elections

  resources :volunteers
  # resources :simple_registrations
  # resources :languages
  # resources :country_languages
  # resources :countries
  # resources :city_languages
  # resources :cities
  # resources :status_languages
  # resources :statuses
  # resources :event_languages
  resources :events
  resources :memberships
  resources :articles
  resources :contacts
  resources :certifications
  resources :abouts
  resources :news
  
  get 'admin' => 'admin#index'
 # You can have the root of your site routed with "root"
  root 'news#index'
  

# OI > Authorization  
#    resources :passwords,
#      controller: 'clearance/passwords',
#      only: [:create, :new]

#    resource :session,
#      controller: 'clearance/sessions',
#      only: [:create]

#    resources :users,
#      controller: 'clearance/users',
#      only: Clearance.configuration.user_actions do
#        resource :password,
#          controller: 'clearance/passwords',
#          only: [:create, :edit, :update]
#      end

#   get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
#   delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'

#    if Clearance.configuration.allow_sign_up?
#      get '/sign_up' => 'clearance/users#new', as: 'sign_up'
#    end
  end
#end

app/models/about.rb
class About < ActiveRecord::Base
  belongs_to :language
  validates_presence_of :lang_id
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :language
  validates_presence_of :lang_id
end

app/models/certification.rb
class Certification < ActiveRecord::Base
  belongs_to :language
  validates_presence_of :lang_id
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :events
  has_many :city_languages, dependent: :destroy
  belongs_to :country
end

app/models/city_language.rb
class CityLanguage < ActiveRecord::Base
  belongs_to :city
  belongs_to :language
  validates_presence_of :city_id
  validates_presence_of :lang_id
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :language
  validates_presence_of :lang_id
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :cities, dependent: :destroy
  has_many :country_languages, dependent: :destroy
end

app/models/election.rb
class Election < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :event_languages, :dependent => :destroy
  has_many :city_languages, through: :cities
  has_many :status_languages, through: :status
  belongs_to :status
  belongs_to :city
  validates_presence_of :status_id
  validates_presence_of :city_id  
  accepts_nested_attributes_for :event_languages
  accepts_nested_attributes_for :status_languages
  accepts_nested_attributes_for :status
end

app/models/event_language.rb
class EventLanguage < ActiveRecord::Base
  belongs_to :event
  belongs_to :language
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_many :certifications
  has_many :articles
  has_many :abouts
  has_many :contacts
  has_many :memberships
  has_many :news
  has_many :country_languages
  has_many :city_languages
  has_many :event_languages
  has_many :status_languages
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :language
  validates_presence_of :lang_id
end

app/models/news.rb
class News < ActiveRecord::Base
  belongs_to :language
  validates_presence_of :lang_id
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :status_languages, dependent: :destroy
  has_many :events
end

app/models/status_language.rb
class StatusLanguage < ActiveRecord::Base
  belongs_to :language
  belongs_to :status
  has_many :events, through: :status
  validates_presence_of :lang_id
  validates_presence_of :status_id
end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
  belongs_to :language
  validates_presence_of :lang_id
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  
  # GET /events
  # GET /events.json
  def index
    # @events = Event.paginate(:page => params[:page], :per_page => 10)
    @events = Event.all.where('status_id <> 4 and status_id <> 5').paginate(:page => params[:page], :per_page => 10)
    @events_done = Event.all.where('status_id = 4').paginate(:page => params[:page], :per_page => 10)
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @event_language = @event.event_languages.first
  end

  # GET /events/new
  def new
    @event = Event.new
    @event.event_languages.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to :controller => 'admin', :action => 'index', notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to :controller => 'admin', :action => 'index', notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to :controller => 'admin', :action => 'index', notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:status_id, :city_id, :start_date, :end_date, :duration, 
          :event_languages_attributes => [:id, :title, :short_event, :body, :author, :lang_id])
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.fields_for(:event_languages) do |el| %>
    <div class="field">
      <%= el.label :title %><br>
      <%= el.text_field :title, :style => "width: 100%;" %>
    </div>
    <div class="field">
      <%= el.label :author %><br>
      <%= el.text_field :author, :style => "width: 100%;" %>
    </div>
    <div class="field">
      <%= el.label :short_event %><br>
      <%= el.text_area :short_event, :style => "width: 100%;" %>
    </div>
    <div class="field">
      <%= el.label :body %><br>
      <%= el.text_area :body, :style => "width: 100%; height: 500px" %>
    </div>
    <div class="field">
      <%= el.label :lang_id %><br>
      <%= el.collection_select(:lang_id, Language.order(:language), :id, :language, {:selected => 1}, include_blank: false)%>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status_id %><br>
    <%= f.collection_select :status_id, StatusLanguage.where('lang_id=1').order(:title), :status_id, :title, include_blank: false %>
  </div>
  <div class="field">
    <%= f.label :city_id %><br>
    <%= f.collection_select :city_id, CityLanguage.where('lang_id=1').order(:title), :city_id, :title, include_blank: false %> 
  </div>

  <div class="field">
  	<%= f.label :start_date %><br>
  	<%= f.datetime_local_field :start_date, :style => "height: 30px; padding-top: 3px"%>
  </div>
  <div class="field">
  	<%= f.label :end_date %><br>
  	<%= f.datetime_local_field :end_date, :style => "height: 30px; padding-top: 3px"%>
  </div>
  <div class="field">
  	<%= f.label :duration %><br>
  	<%= f.text_field :duration %>
  </div>
    
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script src="/assets/tiny_mce/tinymce_init.js" type="text/javascript"></script>

app/views/events/edit.html.erb
<div class="row">
	<div class="col-md-9 sectioncontainer">
		<p style="margin-top: 1.2em;"><%= link_to('Назад', {controller: "admin", action: "index"})%></p>
		<h3>Редактирование мероприятия</h3>
		<%= render 'form' %>
		<br>
	</div>
</div>

app/views/events/index.html.erb
<div class="row">
	
	<div class="col-md-9 sectioncontainer">
		<h3><b>Мероприятия PMI Kyiv Chapter</b></h3>
		<br>
			<h4><b>Предстоящие мероприятия PMI Kyiv Chapter и PMI R.E.P. в Украине</b></h4>		
			<table class='table-blue'>
				<tr class="rowH">
					<th></th>
					<th>Мероприятие</th>
					<th>Статус</th>
					<th>Дата/время начала</th>
					<th>Дата/время окончания</th>
					<th>Длительность (час.)</th>
					<th>Город</th>
				</tr>
				<% @events.order('start_date ASC').each do |event| %>
				<tr class="rowA">
					<td>
			   			<div> 
							<%= link_to event do %>
								<i class="fa fa-file-text fa-lg icon btn btn-info operation_buttons"></i>
							<% end %>
				   		</div>
			   		</td>
					<td>
						<p><%= event.event_languages.first.title %></p>
			   		</td>
					<td>
						<p><%= event.status.status_languages.first.title %></p>
			   		</td>
			   		<td width="100px">
			   			<p><%= event.start_date.to_formatted_s(:rfc822) %></p>
			   		</td>
			   		<td width="100px">
			   			<p><%= event.end_date.to_formatted_s(:rfc822) %></p>
			   		</td>
			   		<td>
			   			<p><%= event.duration %></p>
			   		</td>
			   		<td>
			   			<p><%= event.city.city_languages.first.title %></p>
			   		</td>
				</tr>
				<% end %>
			</table>
		<div class="page_pagination" style="text-align:center"> <%= will_paginate @events %> </div>
				<h4><b>Прошедшие мероприятия PMI Kyiv Chapter и PMI R.E.P. в Украине</b></h4>	
			<table class='table-blue'>
				<tr class="rowH">
					<th></th>
					<th>Мероприятие</th>
					<th>Статус</th>
					<th>Дата/время начала</th>
					<th>Дата/время окончания</th>
					<th>Длительность (час.)</th>
					<th>Город</th>
				</tr>
				<% @events_done.order('end_date DESC').each do |event| %>
				<tr class="rowA">
					<td>
			   			<div> 
							<%= link_to event do %>
								<i class="fa fa-file-text fa-lg icon btn btn-info operation_buttons"></i>
							<% end %>
				   		</div>
			   		</td>
					<td>
						<p><%= event.event_languages.first.title %></p>
			   		</td>
					<td>
						<p><%= event.status.status_languages.first.title %></p>
			   		</td>
			   		<td width="100px">
			   			<p><%= event.start_date.to_formatted_s(:rfc822) %></p>
			   		</td>
			   		<td width="100px">
			   			<p><%= event.end_date.to_formatted_s(:rfc822) %></p>
			   		</td>
			   		<td>
			   			<p><%= event.duration %></p>
			   		</td>
			   		<td>
			   			<p><%= event.city.city_languages.first.title %></p>
			   		</td>
				</tr>
				<% end %>
			</table>
		<br>
		<div class="page_pagination" style="text-align:center"> <%= will_paginate @events %> </div>
	</div>

	<div class="col-md-3 sectioncontainer" style="text-align: center">
		<br>
		<!-- <a href="http://spiderproject.com.ua/community/rating/" target="blank"><img style="-webkit-user-select: none;" src="http://spiderproject.com.ua/upload/bx/608/baner.rating_430x250_5.gif" width="100%" height="100%"></a> --> 
		<br>
		<br>
		<span>Good Things Happen when you Get Involved with PMI!</span>
		<br>
		<br>
	</div>
	
</div>

app/views/events/new.html.erb
<div class="row">
	<div class="col-md-9 sectioncontainer">
		<p style="margin-top: 1.2em;"><%= link_to('Назад', {controller: "admin", action: "index"})%></p>
		<h3>Добавление мероприятия</h3>
		<%= render 'form' %>
		<br>
	</div>
</div>

app/views/events/show.html.erb
<div class="row">
	<div class="col-md-9 sectioncontainer">
		<p style="margin-top: 1.2em;"><%= link_to 'Назад', events_path %></p>
		<div class="panel panel-primary">
			<div class="panel-heading">		
				<h5><b><%= @event_language.title %></b></h5>
			</div>
			<div class="panel-body">
				<table class="table-inner-text">
					<tr>
						<td>
							Дата/время начала:
						</td>
						<td>
							<%= @event.start_date.to_formatted_s(:rfc822) %>
						</td>
					</tr>
					<tr>
						<td>
							Дата/время окончания:
						</td>
						<td>
							<%= @event.end_date.to_formatted_s(:rfc822) %>
						</td>
					</tr>
					<tr>
						<td>
							Продолжительность (час.):
						</td>
						<td>
							<%= number_with_precision(@event.duration, :precision => 1) %>
						</td>
					</tr>
				</table>
				<br>
				<span><%= @event_language.body.to_s.html_safe %></span>
				<table width="100%">
					<tr>
						<td>
							<span style="color: lightgray"><i><%= @event.created_at.strftime("%d/%m/%Y") %>, <%= @event_language.author %></i></span>
		        		</td>
		    		</tr>
		    	</table>
		   </div>
	    </div>
	    
    	<div id="disqus_thread"></div>
		<script type="text/javascript">
    		/* * * CONFIGURATION VARIABLES * * */
    		var disqus_shortname = 'pmiukrainechapter';
   
			/* * * DON'T EDIT BELOW THIS LINE * * */
			(function() {
    			var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
    			dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      			(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
   			})();
		</script>
		<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
		<br>
	    
	</div>
	
	<div class="col-md-3">
		<br>
		<span>Good Things Happen when you Get Involved with PMI!</span>
	</div>
</div>