config/routes.rb
#if Clearance.configuration.routes_enabled?
  Rails.application.routes.draw do

  resources :elections

  resources :volunteers
  # resources :simple_registrations
  # resources :languages
  # resources :country_languages
  # resources :countries
  # resources :city_languages
  # resources :cities
  # resources :status_languages
  # resources :statuses
  # resources :event_languages
  resources :events
  resources :memberships
  resources :articles
  resources :contacts
  resources :certifications
  resources :abouts
  resources :news
  
  get 'admin' => 'admin#index'
 # You can have the root of your site routed with "root"
  root 'news#index'
  

# OI > Authorization  
#    resources :passwords,
#      controller: 'clearance/passwords',
#      only: [:create, :new]

#    resource :session,
#      controller: 'clearance/sessions',
#      only: [:create]

#    resources :users,
#      controller: 'clearance/users',
#      only: Clearance.configuration.user_actions do
#        resource :password,
#          controller: 'clearance/passwords',
#          only: [:create, :edit, :update]
#      end

#   get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
#   delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'

#    if Clearance.configuration.allow_sign_up?
#      get '/sign_up' => 'clearance/users#new', as: 'sign_up'
#    end
  end
#end

app/models/about.rb
class About < ActiveRecord::Base
  belongs_to :language
  validates_presence_of :lang_id
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :language
  validates_presence_of :lang_id
end

app/models/certification.rb
class Certification < ActiveRecord::Base
  belongs_to :language
  validates_presence_of :lang_id
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :events
  has_many :city_languages, dependent: :destroy
  belongs_to :country
end

app/models/city_language.rb
class CityLanguage < ActiveRecord::Base
  belongs_to :city
  belongs_to :language
  validates_presence_of :city_id
  validates_presence_of :lang_id
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :language
  validates_presence_of :lang_id
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :cities, dependent: :destroy
  has_many :country_languages, dependent: :destroy
end

app/models/election.rb
class Election < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :event_languages, :dependent => :destroy
  has_many :city_languages, through: :cities
  has_many :status_languages, through: :status
  belongs_to :status
  belongs_to :city
  validates_presence_of :status_id
  validates_presence_of :city_id  
  accepts_nested_attributes_for :event_languages
  accepts_nested_attributes_for :status_languages
  accepts_nested_attributes_for :status
end

app/models/event_language.rb
class EventLanguage < ActiveRecord::Base
  belongs_to :event
  belongs_to :language
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_many :certifications
  has_many :articles
  has_many :abouts
  has_many :contacts
  has_many :memberships
  has_many :news
  has_many :country_languages
  has_many :city_languages
  has_many :event_languages
  has_many :status_languages
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :language
  validates_presence_of :lang_id
end

app/models/news.rb
class News < ActiveRecord::Base
  belongs_to :language
  validates_presence_of :lang_id
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :status_languages, dependent: :destroy
  has_many :events
end

app/models/status_language.rb
class StatusLanguage < ActiveRecord::Base
  belongs_to :language
  belongs_to :status
  has_many :events, through: :status
  validates_presence_of :lang_id
  validates_presence_of :status_id
end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
  belongs_to :language
  validates_presence_of :lang_id
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    @news = News.paginate(:page => params[:page], :per_page => 10)
    # @events = Event.paginate(:page => 1, :per_page => 5)
    @events = Event.all.where('status_id <> 4 and status_id <> 5')
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to :controller => 'admin', :action => 'index', notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to :controller => 'admin', :action => 'index', notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to :controller => 'admin', :action => 'index', notice: 'News was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :body, :publish_date, :author, :short_news, :lang_id)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :style => "width: 100%;" %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author, :style => "width: 100%;"  %>
  </div>
  <div class="field">
    <%= f.label :publish_date %><br>
    <%= f.text_field :publish_date, :value => Time.now, :style => "width: 100%;"  %>
  </div>  
  <div class="field">
    <%= f.label :lang_id %><br>
    <%= f.text_field :lang_id %>
  </div>
  <div class="field" id="short_news">
    <%= f.label :short_news %><br>
    <%= f.text_area :short_news, :style => 'width: 100%; height: 250px' %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, :style => 'width: 100%; height: 500px' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script src="/assets/tiny_mce/tinymce_init.js" type="text/javascript"></script>

app/views/news/edit.html.erb
<div class="row">
	<div class="col-md-9 sectioncontainer">
		<p style="margin-top: 1.2em;"><%= link_to('Назад', {controller: "admin", action: "index"})%></p>
		<h3>Редактирование новости</h3>
		<%= render 'form' %>
		<br>
	</div>
</div>

app/views/news/index.html.erb
<div class="row">
	
	<div class="col-md-8 sectioncontainer">
		<h3><b>Новости PMI Kyiv Chapter</b></h3>
      <% if @news.present? -%>
        <% @news.order('publish_date DESC').each do |news| %>
          <h4><%= news.title %></h4>
          <span><%= news.short_news.html_safe %></span>
          <table width="100%">
              <tr>
              <td style="text-align: left;">
                <span style="color: gray"><i><%= news.publish_date.strftime("%d/%m/%Y") %>, <%= news.author %></i></span>
                  </td>
              <td style="width: 40%; text-align: right;">
                  <%= link_to 'Читать далее...', news %>
                </td>
              </tr>
            </table>
            <br>
        <% end %>
      <% end -%>
		<br>
		<div class="page_pagination" style="text-align:center"> <%= will_paginate @news %>	</div>
	</div>

	<div class="col-md-4 sectioncontainer" style="text-align: center">
		<br>
		<b><a href="https://marketplace.pmi.org/Pages/QuickMembershipRenewal.aspx?componentcode=C236&returnURL=http%3a%2f%2fwww.pmiukraine.org&language=ua-UA" target="_blank">Быстрая ссылка для продление членства PMI</a></b>
	    <br />
		<span style="text-align: center"><h4>Ближайшие мероприятия</h4></span>
		<div id="accordion" class="box">
        	<% @events.order('start_date ASC').each do |event| %>
	        	<span style="font-size: 13px;">
	        		<%= event.start_date.to_formatted_s(:short)%>, <%= event.city.city_languages.first.title %><br>
	        		<%= event.event_languages.first.title %>
	        	</span>
	            <div class="box">
	                <span><%= event.event_languages.first.short_event.html_safe %></span>
	                <span><%= link_to event do %>Детальная информация...<% end %></span>
	            </div>
	        <% end %>
	    </div>
	    <br>
		<a href="http://spiderproject.com.ua/community/rating/" target="blank"><img style="-webkit-user-select: none;" src="http://www.pmiukraine.org/images/rating2015.gif" width="100%" height="100%"></a> 
	    <br>
	    <br>
		<span>Good Things Happen when you Get Involved with PMI!</span>
		<br>
		<br>
	</div>
</div>

<script type="text/javascript">
    $(function () {
        $("#accordion").accordion({ heightStyle: "content" });
    });
</script>

app/views/news/new.html.erb
<div class="row">
	<div class="col-md-9 sectioncontainer">
		<p style="margin-top: 1.2em;"><%= link_to('Назад', {controller: "admin", action: "index"})%></p>
		<h3>Добавление новости</h3>
		<%= render 'form' %>
		<br>
	</div>
</div>

app/views/news/show.html.erb
<div class="row">
	<div class="col-md-9 sectioncontainer">
		<p style="margin-top: 1.2em;"><%= link_to 'Назад', news_index_path %></p>
		
		<div class="panel panel-primary">

			<div class="panel-heading">			
			<h5><b><%= @news.title %></b></h5>
			</div>
			<div class="panel-body">
			<span><%= @news.body.to_s.html_safe %></span>
			<table width="100%">
				<tr>
					<td>
						<span style="color: lightgray"><i><%= @news.publish_date.strftime("%d/%m/%Y") %>, <%= @news.author %></i></span>
	        		</td>
	    		</tr>
	    	</table>
	    	</div>
	    </div>

	    	<div id="disqus_thread"></div>
			<script type="text/javascript">
	    		/* * * CONFIGURATION VARIABLES * * */
	    		var disqus_shortname = 'pmiukrainechapter';
	   
    			/* * * DON'T EDIT BELOW THIS LINE * * */
    			(function() {
        			var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        			dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
          			(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
	   			})();
			</script>
			<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
			<br>
	    	    	
	</div>
	
	<div class="col-md-3">
		<br>
		<span>Good Things Happen when you Get Involved with PMI!</span>
	</div>
</div>